poetry.lock
pyproject.toml
tests/conftest.py
tests/postgres/postgres/01_init.sql
tests/sql_database/test_sql_database_pipeline.py
tests/sql_source.py
tests/utils.py

Test case for sql pipeline verifying all tables are loaded.  
Adds a db in the docker postgres which is loaded with mock data and used for source.
https://github.com/dlt-hub/pipelines/issues/10

Add test for sql database pipeline

---

README.md
pipelines/chess/__init__.py
pipelines/chess_pipeline.py

1. adds info how to join slack
2. adds parallel execution to chess pipeline

improves readme and chess pipeline

---

pipelines/pipedrive/__init__.py
pipelines/pipedrive/custom_fields_munger.py
pipelines/pipedrive_pipeline.py
poetry.lock
pyproject.toml
tests/pipedrive/test_pipedrive_pipeline.py

Adds pipedrive custom field's renaming capability

---

pipelines/sql_database/__init__.py
pipelines/sql_database/sql_database.py
pipelines/sql_database/util.py
tests/sql_database/sql_source.py
tests/sql_database/test_sql_database_pipeline.py

Addressing some of what's mentioned in https://github.com/dlt-hub/pipelines/issues/25  
* Tests for incremental loading and selected tables
* Using `ConnectionStringCredentials`  
* Some restructuring of the code, organized cursor and table loading logic in a separate module

Sql database pipeline fixes

---

pipelines/sql_database/util.py
tests/sql_database/conftest.py
tests/sql_database/sql_source.py
tests/sql_database/test_sql_database_pipeline.py
tests/sql_database/test_util.py

https://github.com/dlt-hub/pipelines/issues/25
Test table resource incremental loading and column not found errors  
Yield rows in batches

Sql pipeline tests and batch loading

---

.gitignore
init/.dlt/config.toml
pipelines/.dlt/example.secrets.toml
pipelines/github/__init__.py
pipelines/github/queries.py
pipelines/github_pipeline.py
tests/conftest.py
tests/github/test_github_pipeline.py
tests/utils.py

* adds github pipeline with issues, PRs comments and reactions
* loads events incrementally
* disables telemetry when testing

adds github pipeline

---

.github/workflows/get_changed_pipelines.yml
.github/workflows/test_destinations.yml
.github/workflows/test_destinations_slow.yml
pipelines/chess/__init__.py

Implements conditional testing depending on modifications in `pipelines` directory.
Closes #20

Run only tests from modified pipelines

---

pipelines/.dlt/config.toml
pipelines/zendesk/helpers/api_helpers.py
tests/zendesk/test_zendesk.py

Clean- Fix issue with Zendesk Support

---

.github/ISSUE_TEMPLATE/new-verified-pipeline.md

@adrianbr please take a look and the let's rewrite #77 according to it

verified pipeline spec proposal

---

pipelines/.dlt/config.toml
pipelines/google_analytics/__init__.py
pipelines/google_analytics/helpers/credentials.py
pipelines/google_analytics/setup_script.py
pipelines/google_analytics_pipeline.py
poetry.lock

@redicane take a look at this. we had to simplify some signatures and make the pipeline work without config/secret files to run it on colab

ga usage improvements

---

pipelines/hubspot/README.md

Created Hubspot README.md.

---

pipelines/chess/README.md

Created this from docs in dlt/website. Please check @adrianbr

Created Chess README.md

---

pipelines/zendesk/README.md

Please check @adrianbr
issue #

Created README.md for Zendesk

---

pipelines/google_analytics/README.md

Created Google_Analytics README.md

---

pipelines/strapi/README.md

Please Check @adrianbr
issue #

Created README.md for Strapi

---

pipelines/github/README.md

please check @adrianbr
issue #

Updated Github README.md

---

pipelines/pipedrive/README.md

Updated Pipedrive README.md

---

pipelines/zendesk/__init__.py

- [x ] improving, documenting, customizing existing pipeline (please link relevant issue)
https://github.com/dlt-hub/pipelines/issues/112
issue #

add zendesk ticket_events

---

pipelines/.dlt/config.toml
pipelines/.dlt/example.secrets.toml
pipelines/shopify_dlt/__init__.py
pipelines/shopify_dlt_pipeline.py
poetry.lock
pyproject.toml
tests/shopify_dlt/test_shopify_pipeline.py

We could not use the Shopify python sdk but use our own requests implementation, using the sdk produces nicer code, using our requests probably guards against a couple of problems.

Shopify pipeline

---

Makefile
pipelines/asana_dlt/__init__.py
pipelines/asana_dlt/const.py
pipelines/asana_dlt/helpers.py
pipelines/asana_dlt/settings.py
pipelines/asana_dlt_pipeline.py
poetry.lock
pyproject.toml

Example cleanup of a pipeline in our repo

[cleanup] asana pipeline

---

pipelines/github/__init__.py
pipelines/github/helpers.py
pipelines/github/queries.py
pipelines/github/settings.py
pipelines/github_pipeline.py
pyproject.toml
tests/utils.py

[cleanup] GitHub pipeline

---

sources/zendesk_pipeline.py

Fix: fixed typing

---

sources/asana_dlt/README.md

- [ X] improving, documenting, customizing existing source (please link an issue or describe below)
issue #
Added README.md to be loaded with dlt init

Added Asana verified source README.md

---

sources/mux/README.md

Mux README.md

---

sources/matomo/README.md

- [ Y] improving, documenting, customizing existing source (please link an issue or describe below)
issue #

Docs/matomo readme.md

---

sources/salesforce/README.md

issue #
Added Salesforce README.md

Salesforce README.md

---

sources/notion/README.md

issue #
Updated Notion README.md

Updated Notion README.md

---

sources/google_analytics/README.md

Update Google Analytics README.md

---

sources/shopify_dlt/README.md

Shopify README.md

---

sources/strapi/README.md

Updated Strapi README.md

---

sources/zendesk/README.md

- [ Y] improving, documenting, customizing existing source (please link an issue or describe below)
issue #

Updated Zendesk README.md

---

sources/stripe_analytics/README.md

Created Stripe README.md

---

sources/workable/README.md

- [ Y] improving, documenting, customizing existing source (please link an issue or describe below)
issue #

Created Workable README.md

---

CONTRIBUTING.md

Docs: CONTRIBUTING refactoring

---

sources/pipedrive/__init__.py
sources/pipedrive/settings.py

added a new endpoint `leads` to the pipedrive source. We needed to extract data from this endpoint, which is why we previously implemented it within our pipedrive pipeline. Now adding this endpoint to the source code to make it publicly available.
issue #

add leads endpoint to pipedrive source

---

sources/zendesk_pipeline.py

Related to https://github.com/dlt-hub/verified-sources/issues/224
Source arguments were changed, now also updated to match in the pipeline examples

Update start_/end_time argument names in zendesk pipeline example

---

sources/google_analytics_pipeline.py

delete TRunMetrics from typing

---

sources/google_sheets/README.md
sources/google_sheets/__init__.py
sources/google_sheets/helpers/api_calls.py
sources/google_sheets/helpers/data_processing.py
sources/google_sheets_pipeline.py
tests/google_sheets/test_google_sheets_source.py

skips blank columns, adds demo for multiple spreadheets and table rename

---

sources/chess/README.md

- [ y] improving, documenting, customizing existing source (please link an issue or describe below)
issue #

Update Chess README!

---

sources/google_sheets_pipeline.py

Google sheets: remove hardcode

---

sources/sql_database/helpers.py

Fixes https://github.com/dlt-hub/verified-sources/issues/255

Yield sql db rows in batches

---

sources/airtable/__init__.py
sources/airtable_pipeline.py

Rearranged airtable_pipeline.py as per other pipelines, added doc strings, and mapped the base_id and table names to dlt.config.value.
- [X ] improving, documenting, customizing existing source (please link an issue or describe below)
issue #

Rearranging structure, adding doc strings and mapping to config.toml

---

sources/airtable/__init__.py
sources/airtable/requirements.txt

issue #
1. removes outdated documentation: all write dispositions can be customized in pipeline.run() method
2. requires dlt 0.3.17 for invocation of simplified `apply_hints` API

Airtable: updates dependency

---

sources/airtable/README.md

- [X ] improving, documenting, customizing existing source (please link an issue or describe below)
issue #

Updated Airtable README

---

sources/mongodb/helpers.py
tests/mongodb/test_mongodb_source.py

There was a bug when converting Ids and decimals inside nested objects, this PR fixes that and also adds tests to these cases. A testing object was added to the db for that.

fix mongo conversion issue

---

sources/mongodb/README.md

- [ X] improving, documenting, customizing existing source (please link an issue or describe below)
issue #

Updated Mongodb README.md

---

sources/jira/__init__.py
sources/jira/settings.py
tests/jira/test_jira_source.py

Adds more robust pagination and tests for paginated results

improves pagination, adds tests to jira

---

sources/inbox/__init__.py
sources/inbox_pipeline.py
tests/inbox/test_inbox.py

fix data_hash, deleted hardcode in pipeline

---

sources/mongodb/__init__.py
sources/mongodb/helpers.py
sources/mongodb_pipeline.py
tests/mongodb/test_mongodb_source.py

issue #280
Add parallel processing to mongo source and improve the chunking in the ST version.

Add parallel mongoDB

---

sources/personio/README.md
tests/personio/test_personio_source.py

Updated Personio README

---

sources/kinesis/README.md

Updated Kinesis README.
issue #

Updated Kinesis README.md

---

sources/personio/README.md

add more endpoints

---

sources/filesystem/__init__.py
tests/filesystem/test_filesystem.py

Show and fix a bug
[issue 321](https://github.com/dlt-hub/verified-sources/issues/321)
Note that the automated test doesn't work yet but bug and fix can be observed by debugging the test.   Test needs to take into account that pipe.py unchunks the output already.

Fix filesystem chunk bug #321

---

sources/sql_database/README.md
sources/sql_database_pipeline.py
tests/sql_database/test_sql_database_source.py

The rfam database currently yields access denied for the rfamro user. I have migrated to another public genome database called ensembl.

fix tests and documentation depending on rfam database

---

tests/kafka/test_kafka.py

To avoid flaky errors because of slow Kafka sync, it's proposed to use mocks. It'll allow to test the functionality, not dealing with a real Kafka service, thus, all the sync errors will become not actual.

test(kafka): use mocks instead of reading from Kafka cluster

---

sources/sql_database/README.md
sources/sql_database_pipeline.py
tests/sql_database/test_sql_database_source.py

Revert "fix tests and documentation depending on rfam database (#328)"

---

CONTRIBUTING.md
README.md

Update community links to new redirect link on dlthub website

update community links

---

sources/sql_database/schema_types.py
sources/sql_database_pipeline.py

sql alchemy + connector x example

---

sources/notion/helpers/database.py

fix(notion): define payload within the while-loop

---

pytest.ini

issue #344 
Even better would be probably to upgrade these dependencies, but I'm unsure which they are and how to find that out

Silences deprecation warnings caused by google dependencies.

---

sources/rest_api/__init__.py

issue #313 
- allows specification of SinglePagePaginator
- reactors small redundancy

[REST source] 

---

sources/stripe_analytics_pipeline.py
tests/stripe_analytics/test_stripe_source.py

issue #
I commented all other examples

Stripe: load only all data in pipeline example 

---

tests/rest_api/test_rest_api_source.py

issue #313 
Currently, failing test case

[REST source] test case for dependent resource

---

tests/kinesis/test_kinesis.py

Makes kinesis tests work again

fixes kinesis shard test

---

sources/rest_api/__init__.py
sources/rest_api/client.py
sources/rest_api/detector.py
sources/rest_api/typing.py
tests/rest_api/test_detector.py

1. expects dlt 0.4.6
2. see commit log for changes

[REST CLIENT] alt response extractor

---

sources/rest_api/README.md

Initial version of the README.md

---

sources/rest_api/paginators.py
tests/rest_api/conftest.py
tests/rest_api/test_client.py
tests/rest_api/test_paginators.py

This PR backports RESTClient implementation from the dlt core repo.

Backport RESTClient from the dlt core

---

sources/rest_api_pipeline.py

This PR removes `check_connection` from the GitHub pipeline to make the example simpler.

Simplify GitHub example pipeline

---

sources/kafka/helpers.py
sources/mongodb/__init__.py
sources/mongodb/helpers.py
sources/rest_api/auth.py
sources/sql_database/helpers.py
sources/zendesk/helpers/credentials.py

Prepares config specs in verified sources to work well with 0.4.8 (automatic typing and initializers)

adds defaults to fields in specs

---

sources/notion/__init__.py
tests/notion/test_pages_resource.py

feat(notion): add pages resource

---

.github/workflows/init.yml
.github/workflows/lint.yml
.github/workflows/test_all_sources_nigthly.yml
.github/workflows/test_destinations_slow.yml
.github/workflows/test_on_local_destinations.yml
.github/workflows/test_on_local_destinations_forks.yml
poetry.lock
pyproject.toml
sources/filesystem/readers.py
sources/filesystem_pipeline.py
sources/google_ads/setup_script_gcp_oauth.py
sources/sql_database/helpers.py
sources/sql_database/schema_types.py
tests/conftest.py
tests/filesystem/settings.py
tests/filesystem/test_filesystem.py
tests/sql_database/sql_source.py

restores sql alchemy 14 in sql_database

---

sources/rest_api/__init__.py
sources/rest_api/config_setup.py
sources/rest_api/utils.py
tests/rest_api/test_configurations.py

Update rest_api functions to not modify the config dict

---

sources/sql_database_pipeline.py

Updated sql_database comments.

Updated sql_database comments

---

sources/rest_api/__init__.py
sources/rest_api/config_setup.py
sources/rest_api_pipeline.py
tests/rest_api/source_configs.py
tests/rest_api/test_configurations.py

1. makes sure that "path" is fully bound to params
2. nicer exceptions for resolve params leading to a unknown resource name
3. friendly exception when keys not found in parent record

rest_api: adds custom exceptions, some edge cases and tests

---

tests/kafka/test_kafka.py

test(kafka): add a test for offsets reset

---

poetry.lock
pyproject.toml
sources/google_ads/requirements.txt

fix(google_ads): add missing dependency

---

sources/pipedrive/helpers/custom_fields_munger.py
sources/pipedrive_pipeline.py
sources/sql_database/helpers.py
tests/pipedrive/test_pipedrive_source.py
tests/sql_database/test_helpers.py
tests/sql_database/test_sql_database_source.py
tests/utils.py

sort order was generated without takin `last_value_func` into account, this PR corrects that and adds tests

[sql_database] generates correct sort order sql

---

poetry.lock
pyproject.toml
sources/google_sheets/helpers/data_processing.py
sources/mongodb/__init__.py
sources/mongodb/helpers.py
tests/mongodb/test_mongodb_source.py

feat(mongodb): support incremental end_value

---

sources/mongodb/__init__.py
sources/mongodb/helpers.py
tests/mongodb/test_mongodb_source.py

feat(mongodb): support limit in the source

---

sources/sql_database/helpers.py

Add fallback value for `tz` in `row_tuples_to_arrow` (sql_database helpers)

---

sources/pg_replication/schema_types.py

`pg_replication` was directly importing capabilities. this will be soon discontinued. caps are accessed via the destination factory and type mapper is cached.

fixes usage of capabilities, caches type mapper in pg_replication

---

tests/rest_api/test_configurations.py

Implement additional test for default resource settings merging

---

sources/pg_replication/helpers.py
sources/rest_api/config_setup.py
tests/mongodb/test_mongodb_source.py

This PR fixes code formatting errors. Let's merge it so that we don't have to select which files to include after having run `make format`.

fix: formats code

---

tests/rest_api/test_configurations.py

Removes debug print in test suite
Follow-up to https://github.com/dlt-hub/verified-sources/pull/556

rest_api: remove debug print from test suite

---

sources/rest_api/README.md

I’m just fixing a bracket typo I found while exploring the RestAPI docs. 😅 
I’ve started exploring the dlt package and I'm following the docs to run some tests. 
You’re doing an awesome job! 👏🏻

removing bracket typo from `rest_api` docs

---

ai/cursor/.cursor/rules/build-rest-api.mdc
ai/cursor/.cursor/rules/dlt.mdc
ai/cursor/.cursor/rules/rest_api_extract_parameters.mdc
ai/cursor/.cursor/rules/rest_api_pagination.mdc
sources/hubspot/__init__.py
sources/jira/__init__.py
sources/pipedrive/__init__.py
sources/unstructured_data/__init__.py
uv.lock

This PR adds descriptions to rules that have been missing them. Sets `alwaysApply` to true. Includes minuscule changes to confusing example reference.

Minor adjsutments to cursor rules
