pipelines/sql_database/source.py
pipelines/sql_database_pipeline.py

I'm experimenting with making the SQL pipeline resumable, so it only reads rows not included in the previous run.  https://github.com/dlt-hub/pipelines/issues/10
Works by setting a `cursor_column` and optionally also `unique_column` (could be pk or some other unique field) in config, e.g. `config.toml`
```toml
[sources.some_table_name]
cursor_column = "updated_at"
unique_column = "id"
```
In dlt.state I store the last value of the cursor column and all unique ids for rows with that same cursor value.  
Good for the case where e.g. cursor is a timestamp for last update, then the unique column makes sure we don't miss rows in case of updates with same timestamp without having to store id of every row loaded in `dlt.state`.
For subsequent runs of the pipeline it generates queries like this …

Make SQL pipeline resumable.

---

pipelines/pipedrive/__init__.py
pipelines/pipedrive/custom_fields_munger.py
tests/pipedrive/test_pipedrive_pipeline.py

Custom enum fields are now mapped to the string label instead of the ID of the enum value
fixes #119
TODO:

Map pipedrive custom field enum values to labels

---

pipelines/.dlt/example.secrets.toml
pipelines/sql_database/sql_database.py
pipelines/sql_database_pipeline.py
tests/sql_database/test_sql_database_pipeline.py

Adds usage examples for the sqlalchemy pipeline.   
* Using the sql_database source in multiple configuration with explicit credentials
* sql_database source to load entire database
* Using the standalone resource to load some known tables
Changed the standalone table resource to be a normal function wrapped in `with_config`. The nested resource causes issues with the incremental wrapper
closes #75

Sql database examples

---

sources/hubspot_pipeline.py
tests/hubspot/test_hubspot_source.py

issue #
- We found out when the  then the pipeline will try ti create the dataset with a suffix as a timestamp, and we want to enable people to use their own datasets or schemas (depends on the destination)

Remove full_refresh args in Hubspot pipeline

---

sources/pipedrive/README.md

Updated Pipedrive  README.md

---

README.md
docs/DISTRIBUTION.md

This PR corrects links to documentation.
The page https://dlthub.com/docs/walkthroughs/add-a-pipeline does not exist anymore. It's now https://dlthub.com/docs/walkthroughs/create-a-pipeline.
Please correct the link also in the repo description:

fixes link to create-a-pipleine docs page

---

check-package.sh
mypy.ini
poetry.lock
pyproject.toml
sources/jira_pipeline.py
sources/stripe_analytics_pipeline.py

Related to https://github.com/dlt-hub/verified-sources/issues/224
* `sources/__init__.py` file is deleted, don't think it's needed -> mypy can now follow imports in pipeline scripts and check them properly.   
* Disable `ignore_missing_imports` by default. Enabling it globally silently ignores any misspelled module names and such -> instead ignore only the specific packages which are missing type hints.

Improve type checking in sources

---

.github/workflows/test_on_local_destinations.yml
.github/workflows/test_on_local_destinations_forks.yml
CONTRIBUTING.md
poetry.lock
pyproject.toml
sources/google_sheets/README.md
sources/google_sheets/__init__.py
sources/google_sheets/helpers/api_calls.py

- we are fixing misplaced blake in pyproject.toml: (poetry does not update the toml file if other tool table is in the middle of the project)
- we are separating the forks ci runs

separates forks ci

---

sources/facebook_ads/__init__.py
sources/facebook_ads/helpers.py
tests/facebook_ads/test_facebook_ads_source.py

The helper function **get_start_date()** is using the **parse_iso_like_datetime()** function to convert the ISO datetime string into pendulum.datetime object. The **parse_iso_like_datetime()** function can not handle ISO date string and returns an datetime.date object instead of a pendulum.datetime object.
I replace the **parse_iso_like_datetime()** with **ensure_pendulum_datetime** function inside the  **get_start_date()**. I also wrote some test to ensure that pendulum.datetime is returned.

Facebook ads datetime object conversion fix.

---

.github/workflows/test_on_local_destinations_forks.yml
CONTRIBUTING.md

issue #247 
Changes "fork" workflow to use `pull_request_target` to run PRs in context of the upstream repo:
- if upstream repo and PR repo are same (so this is not a fork) - we always run the workflow
- otherwise we run only when `ci from fork` label is assigned to PR. we assign this label only when code is reviewed and accepted

allows running "fork" CI workflow in context of upstream repo

---

sources/facebook_ads/__init__.py
sources/facebook_ads/settings.py

issue #250 
facebook_insight resource cast all fields as strings. Fixing datatype for the default insight fields.

Facebook Insight Resource Fixing Field Data Types

---

sources/pipedrive/__init__.py
sources/pipedrive/helpers/pages.py
tests/pipedrive/test_pipedrive_source.py

- [x ] fixing a bug (please link a relevant bug report)
`pipedrive_api_key` as received by the source was not passed to resources which resulted in injecting the default

passed api key to resoures explicitly

---

sources/inbox/README.md

- [X ] improving, documenting, customizing existing source (please link an issue or describe below)
issue #
Standardized the Inbox README.

Updated Inbox Readme

---

sources/sql_database/helpers.py
tests/sql_database/sql_source.py

for some reason, using partition() without `size` yields all results at once, ignoring `yield_per` setting.

fixes yielding partitions in sql_database

---

sources/filesystem/README.md

- [ X] improving, documenting, customizing existing source (please link an issue or describe below)
issue #

Updated filesystem readme.md

---

sources/hubspot/__init__.py
sources/hubspot/helpers.py
sources/hubspot/settings.py
sources/hubspot_pipeline.py
tests/hubspot/test_hubspot_source.py

Fixes #305 
The error `414 URI too long` happens, because we request the list of all the possible properties for an object here:
https://github.com/dlt-hub/verified-sources/blob/a1cf60a718389f63b1b73b3a6e1c92432ee7c269/sources/hubspot/helpers.py#L165-L184
In some cases, object has so many properties, that their list joined by `,` becomes longer than 8000 of symbols, which causes `414`.
**Proposed solution**:
Instead of reading all the possible properties (most of which are very low-level and unlikely needed, like number of the broker, which processed the record), we create a default list of properties for every endpoint. The default lists are copied from the Hubspot `search` (see https://developers.hubspot.com/docs/api/crm/search#crm-objects), so for Hubspot users it should be an expected …

fix(hubspot): provide default lists of properties

---

poetry.lock
pyproject.toml
sources/sql_database/__init__.py
sources/sql_database/helpers.py
sources/sql_database/settings.py
sources/sql_database_pipeline.py
tests/sql_database/test_sql_database_source.py

Improvements to `sql_database`
1. reflect tables at runtime - best option for Airflow
2. table adapter callback - ie. to select columns to replicate
3. control buffer sizes in SqlAlchemy

allows for delayed table reflection, column selection and buffer control in sql_database

---

sources/rest_api/__init__.py

#313 
This PR enhances the generic rest API source to supports all authentication methods, e.g. HTTP basic or subclasses of AuthBase.

REST API: support all authentication methods

---

sources/rest_api/__init__.py

issue #313 
This PR allows adding arbitrary fields from the parent resource in the child resource. Example: In Workable, [jobs/{shortcode}/recruiters](https://workable.readme.io/reference/new-jobsshortcoderecruiters) does not include the jobs shortcode. Thus, the response does not tell to which job a recruiter belongs.
For example, a child resource can be specified as follows in order to include `confidential` and `id` from the `jobs` resource in the `jobs_id_approval_flows` resource:
```
"jobs/{id}/approval_flows": {
"params": {
"id": ResolveConfig("jobs", "id"),
},
"resource": {**default_resource_config, "include_from_parent": ["confidential", "id"]},
}
```
The resulting fields in the child resource are `_jobs_confidential` and `_jobs_id`.
Marked yellow: The parent's resource name is …

Generic API client: include parent fields in child resource

---

sources/rest_api/paginators.py

References #313 
The Workable API does not include the json path to the next page for the last page of the response. Thus, this PR catches such cases.

Rest API: Ends pagination if next page path is not in response.json()

---

sources/rest_api/__init__.py
sources/rest_api_pipeline.py

issue #313 
as discussed, this name appears to be clearer because not other key uses "default" and the class property is called "paginator".

[REST Source] renames default_paginator argument to paginator

---

sources/rest_api/__init__.py

issue #313
I forgot to commit this file in https://github.com/dlt-hub/verified-sources/pull/367. This PR completes that refactoring.

[REST Source] completes renaming of default_paginator to paginator

---

sources/bing_webmaster_pipeline.py
tests/bing_webmaster/test_bing_webmaster_source.py

Dlthub's CI has an API key that allows only access to dlthub.com and not other domains.

[bing webmaster] changes test suite to fit dlthub's CI secrets

---

sources/rest_api/__init__.py
sources/rest_api_pipeline.py

issue #313 
This PR adds a convenience function to test whether a configuration can connect to the API endpoint.
1. allows easy checking if credentials are correct. Especially when dlt is embedded and used as a fivetran-type data platform where pipeline users enter their credentials in some UI or config file.
2. provides a clear way to test authentication, especially in the absence of an [auth verification endpoint](https://docs.datadoghq.com/api/latest/authentication/)
See demo in `rest_api_pipeline.py` for ways of using this function.
Requires awareness of the developer that it yields from the source. If a call to `check_connection()` is part of a pipeline run, it must be used with a separate source object to avoid losing data.
I tried calling `copy.deepcopy` on the source argument, but …

[REST API source] adds function to check connection

---

sources/rest_api/client.py

issue #313 
Before:
```
2024-02-29 18:51:47,000|[INFO                 ]|5743|8123666432|dlt|client.py|make_request:62|Making GET request to https://testing.workable.com/spi/v3/candidate/138d8abe/offer with params={'limit': '100'}, json=None
2024-02-29 18:51:47,356|[INFO                 ]|5743|8123666432|dlt|client.py|paginate:120|Ignoring response and stopping pagination.
```
After:
```
2024-02-29 18:51:47,000|[INFO                 ]|5743|8123666432|dlt|client.py|make_request:62|Making GET request to https://testing.workable.com/spi/v3/candidate/138d8abe/offer with params={'limit': '100'}, json=None
2024-02-29 18:51:47,356|[INFO                 ]|5743|8123666432|dlt|client.py|paginate:120|Error 404. Ignoring response '{'result': 'NOT_FOUND', 'message': 'The requested resource is not …
```

[REST] Detailed error handler logging

---

sources/sql_database/helpers.py
sources/sql_database/schema_types.py

Hides sql alchemy generic types so we can drop sql alchemy dep in `dlt` core

hides sql alchemy generics

---

tests/rest_api/conftest.py

issue #313 
```
See https://setuptools.pypa.io/en/latest/pkg_resources.html
import pkg_resources
tests/rest_api/conftest.py:75
dlt-verified-sources/tests/rest_api/conftest.py:75: DeprecationWarning: invalid escape sequence '\?'
@router.get("/posts(\?page=\d+)?$")
tests/rest_api/conftest.py:79
dlt-verified-sources/tests/rest_api/conftest.py:79: DeprecationWarning: invalid escape sequence '\d'
@router.get("/posts/(\d+)/comments")
tests/rest_api/conftest.py:84
dlt-verified-sources/tests/rest_api/conftest.py:84: DeprecationWarning: invalid escape sequence '\d'
@router.get("/posts/\d+$")
tests/rest_api/conftest.py:89
dlt-verified-sources/tests/rest_api/conftest.py:89: DeprecationWarning: invalid escape sequence '\d'
@router.get("/posts/\d+/some_details_404")
-- Docs: …
```

[REST source] fixes deprecation warning

---

sources/slack/__init__.py
sources/slack/helpers.py
sources/slack_pipeline.py
tests/slack/test_slack_source.py

* Now all messages are extracted into one table instead of a table per channel. 
* Add replies resource. Now replies are also extracted by slack source

Squash messages to one table for slack

---

sources/facebook_ads/README.md
sources/kafka_pipeline.py
sources/matomo/README.md
sources/personio/README.md
sources/sql_database/requirements.txt
sources/strapi/README.md
tests/facebook_ads/test_facebook_ads_source.py
tests/kinesis/test_kinesis.py
tests/matomo/test_matomo_source.py
tests/personio/test_personio_client.py
tests/personio/test_personio_source.py

Fix: skip tests for sources without test accounts

---

.github/workflows/init.yml
.github/workflows/lint.yml
.github/workflows/test_on_local_destinations.yml
.github/workflows/test_on_local_destinations_forks.yml
sources/rest_api/__init__.py
sources/rest_api/client.py
sources/rest_api/detector.py
sources/rest_api/typing.py
sources/rest_api/utils.py
tests/rest_api/test_client.py
tests/rest_api/test_detector.py
tests/rest_api/test_rest_api_source.py
tests/rest_api/test_rest_api_source_offline.py

1. guesses the single entity endpoints from the path when creating resources
2. NOTE: data_selector is JSONPath now, backward compatile with string names
3. yielded page data is an extended list with requests context
4. all tests are passing

[REST CLIENT] yields data pages with requests context

---

.github/workflows/test_all_sources_nigthly.yml
sources/kafka/README.md
sources/personio/README.md
tests/kafka/test_kafka.py

issue #
We need to check all our verified sources sometimes. We test them, but only when create or change them.  They break silently all the time, and we find out about it from users or by accident.
Suggestion: we could have a nightly run, every night at 4am or so

test all sources every night

---

sources/rest_api/paginators.py

This is a temporary fix for the issue of duplication of query string parameters in URL-based paginators.

Temp fix for duplicate query string params in URL-based paginators

---

sources/kafka/requirements.txt

Unpin the dlt dependency for the Kafka source.
- Fixes #414

Remove upper bound on dlt dependency in Kafka source

---

sources/workable/__init__.py

Given that there's no primary key set for candidate sub-resources, we should just use `append`
issue #

fix(Workable): use append write disposition for candidate subresources

---

sources/rest_api/__init__.py
sources/rest_api/typing.py
tests/rest_api/conftest.py
tests/rest_api/source_configs.py
tests/rest_api/test_configurations.py
tests/rest_api/test_rest_api_source_offline.py

This PR updates rest_api source to allow specifying:
- JSON payload for non-dependent (parent) resources.
- Custom HTTP headers in the client config.

rest_api: allow JSON payload and custom headers

---

Makefile
poetry.lock
pyproject.toml
sources/filesystem/readers.py
sources/inbox/helpers.py
sources/pg_replication/__init__.py
sources/pg_replication/helpers.py
sources/rest_api/__init__.py
sources/rest_api/config_setup.py
sources/rest_api/exceptions.py
sources/rest_api/typing.py
sources/rest_api_pipeline.py
sources/unstructured_data/inbox/__init__.py
sources/unstructured_data/inbox/helpers.py
tests/rest_api/source_configs.py
tests/rest_api/test_configurations.py
tests/rest_api/test_rest_api_source_offline.py

1. updates `ResourceBase` to accept all the current resource decorator hints
2. updates mypy to one used by dlt
3. fixes a few rest api tests
4. types paginator configs to match signatures in REST Client
5. merges ResourceEndpoint keeping TypedDict as a whole
6. renames paginator shorthands to match REST Client
```
header_links -> header_link
json_links -> json_response
```
7. adds typed dicts for `incremental` and `resolve` params
8. changes how single entity endpoints are handled
9. adds tests for the above
fixes: #445 
fixes: #455

Updates resource base  config in rest api

---

init/pipeline.py
init/pipeline_generic.py

This PR updates `pipeline_generic` to use `RESTClient` to make requests.
Resolves: https://github.com/dlt-hub/verified-sources/issues/448

Use RESTClient in generic template

---

sources/pipedrive_pipeline.py
tests/pipedrive/test_pipedrive_source.py

we have no data in our Pipedrive test account (only "leads"), skip some tests for now

Pipedrive: fix tests

---

sources/pipedrive/README.md

Added a note: 
> Note, the `deals_flow` and `deals_participants` resources are built based on the "deals" resource. Therefore, it’s a good practice to load them together in one source.

Updated pipedrive README.md

---

sources/kafka/__init__.py

See #450.
Don't subscribe after assigning partitions and offsets.
- Fixes #450

kafka: don't subscribe after consumer has been assigned

---

sources/rest_api/config_setup.py
sources/rest_api/typing.py
tests/rest_api/test_configurations.py

This pull request adds ability to use JSONPath in [path parameter resolve configuration](https://dlthub.com/docs/dlt-ecosystem/verified-sources/rest_api#define-resource-relationships):
Example:
Suppose you have parent resource data item like:
```
{
"number": 42,
"nested_data": {
"some_nested_identifier": 24,
...
}
}
```
Before this PR you could only refer the `number` field, like so: 
```
{
"resources": [
...
{
"name": "issue_comments",
"endpoint": {
"path": "issues/{issue_number}/comments",
"params": {
"issue_number": {
"type": "resolve",
"resource": "issues",
"field": "number",
}
},
},
},
],
}
```
With this PR you can also refer `nested_data.some_nested_identifier` field by using JSONPath:
```
{
"resources": [
...
{
"name": "issue_comments",
"endpoint": {
"path": …
```

reset_api: allow JSONPath in field value in ResolveParamConfig

---

sources/sql_database/__init__.py
tests/sql_database/sql_source.py
tests/sql_database/test_sql_database_source.py

- Add flag `include_views` to `sql_database` source to enable reflecting views
- Test for the flag
- Test for `sql_table` works when the table name is a view
- Test for `sql_database` always includes views when they're passed in `table_names` regardless of the `include_views` flag
- Resolves #459

sql_database: Add flag to include views with reflected tables

---

sources/github/__init__.py
sources/github/helpers.py
sources/github/queries.py
sources/github_pipeline.py
tests/github/test_github_source.py

This PR adds a new resource for github stargazers. It provides the github user info (login, url, avatar) and the starred_at for every repo. The data is fetched using graphql and the full history is available.
not related to any issue
- not related to this PR but I was not able to install the pre-requisites with python 3.12 : multidict is not compatible, so I have moved to 3.8 as suggested by the contribution guideline
- unfortunately it is not possible to get forks/watchers with date from github graphql api

feat(github): add stargazers

---

sources/filesystem/helpers.py

Due to changed semantics introduced in https://github.com/dlt-hub/dlt/pull/1430#issue-2329339449. The fix is backward compatible

fixes config injection defaults in filesystem

---

sources/pg_replication/exceptions.py
sources/pg_replication/helpers.py
sources/pg_replication/requirements.txt
sources/pg_replication_pipeline.py
tests/test_dlt_init.py

Fixes https://github.com/dlt-hub/dlt/issues/1490
- makes `sql_table` import from external `sql_database` source conditional on `persist_snapshots` argument, so users only have to run `dlt init sql_database ...` if they want to do an initial load
- fixes destination for "source pipeline" in example pipelines to `postgres` using workaround, so it doesn't get replaced during `dlt init` 
- adds explicit `credentials` argument when creating `sql_client` from `Pipeline` object, so no `destinations.postgres.credentials` block is included in the generated `secrets.toml` 
- bumps `dlt` requirement to version `0.13`, because it relies on the fix in https://github.com/dlt-hub/dlt/pull/1499/files 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - …

fix: `pg_replication` example pipeline issues

---

sources/notion/__init__.py
tests/notion/test_pages_resource.py

fix(notion): pages resource returns only meta info

---

sources/sql_database/schema_types.py

Oracle NUMBER type derives both from Numeric and Integer and is used to represent decimals and float (integers have separate type)
```py
class NUMBER(sqltypes.Numeric, sqltypes.Integer):
__visit_name__ = "NUMBER"
```
type inference was changed so Numeric is checked first and then integers

derive decimal type from sql alchemy before attempting integers

---

sources/sql_database/__init__.py
sources/sql_database/helpers.py
tests/sql_database/test_arrow_helpers.py
tests/sql_database/test_sql_database_source.py

sql alchemy engines created for each `sql_table` were not disposed after use. now they are. we also garbage collect after every test to dispose `sql_database` wide engines.
for full control pass your own engine instances

[sql_database] disposes sql alchemy engines created per table

---

sources/rest_api/config_setup.py
tests/rest_api/test_configurations.py

- implementing verified source (please link a relevant issue labeled as `verified source`)
- anything else (please link an issue or describe below)
- fixes bug where configuring two incremental configs in one endpoint resource would not raise an error
- throws error if request param is configured with unsupported and illogical incremental config
- Resolves #518

rest_api: Fix/518 prevent unsupported incremental configs

---

tests/rest_api/conftest.py
tests/rest_api/test_rest_api_source_offline.py

- improving, documenting, or customizing an existing source
This is a follow-up to #507 
The previous test implementation relied on a mock server to listen to a specific route and return the data inside the request parameters.
Now, we mock the request-sending method and assert that it was called with the expected parameters.
This makes the test run faster and uses less code.

rest_api: refactors incremental API call test to mock

---

sources/rest_api/typing.py
tests/rest_api/test_configurations.py

This PR:
- Corrects the type declaration of the PageNumberPaginator
- updates the existing test
- includes a regression test
- Fixes https://github.com/dlt-hub/dlt/issues/1616

Fix: 1616 makes it possible to configure the base_page for PageNumberPaginator

---

sources/rest_api/config_setup.py
sources/rest_api/typing.py
tests/rest_api/test_configurations.py

- fixing a bug:
- code formatting
- Fixes #...
- Closes #...
- Resolves #...

rest_api paginator: Allows using json_response in place of json_link

---

sources/rest_api/config_setup.py

rest_api: Fix default resource endpoint params merging

---

tests/rest_api/test_configurations.py

implements regression test for #535

---

tests/rest_api/test_configurations.py

rest_api paginator: Allows using JSONResponsePaginator in place of JSONLinkPaginator
- Resolves: https://github.com/dlt-hub/dlt/issues/1632

rest_api paginator: Allows using JSONResponsePaginator 

---

sources/rest_api/config_setup.py
tests/rest_api/test_configurations.py
tests/rest_api/test_paginators.py

- improving an existing source  #514 
- Implements #514

Feat/514 rest_api: pluggable paginators

---

poetry.lock
pyproject.toml
sources/rest_api/config_setup.py
sources/rest_api/typing.py
tests/rest_api/test_configurations.py
tests/rest_api/test_rest_api_source_offline.py

This PR:
1. renames the incremental config key `transform` to `convert`
2. deprecates the old `transform` so that it still works but issues a warning
- Resolves #544

rest_api: changes incremental configuration from `transform` to `convert`

---

sources/rest_api/__init__.py
sources/rest_api/config_setup.py
sources/rest_api/typing.py
tests/rest_api/test_configurations.py
tests/rest_api/test_paginators.py

fixing a bug (please link a relevant bug report)
The masking of secrets works as follows:
1. deepcopy the configuration dict
2. take the `auth` configuration and replace all values for allowed sensitive keys with masked versions
3. validate the deep copy where sensitive values are replaced
Assumption:
Authentication objects that are not dictionaries are expected not to print their sensitive values when `__str__()` is called.
Complexity:
- The auth configuration allows both config dictionaries and specific classes. Thus, we need to do runtime type checks.
- implementing polymorphic dispatch, e.g. `auth_config.mask_secrets()` for dicts that are also callable (HttpBasicAuth, BearerTokenAuth, APIKeyAuth) requires an update in the dlt core library. See implementation here: …

rest_api: mask secrets in config

---

sources/sql_database/__init__.py
sources/sql_database/helpers.py
sources/sql_database/schema_types.py
sources/sql_database_pipeline.py
tests/sql_database/test_helpers.py
tests/sql_database/test_sql_database_source.py

This adds `included_columns` option for sql database ( I would have named it `columns` but that was conflicting with the `$COLUMNS` shell variable in config resolution)   
Can be set with argument or config in in the standalone resource, and with config in the database source, e.g.:
```toml
[sources.sql_database.campaign]
included_columns = ["id", "name", "created_at", "updated_at"]
```
One part of https://github.com/dlt-hub/verified-sources/issues/531#issuecomment-2267646842  
The query editing callback I would do in another PR

SQL database: included_columns option

---

sources/salesforce/README.md

A follow-up to https://github.com/dlt-hub/dlt/pull/1665

salesforce: fix typo in README.md

---

sources/sql_database/__init__.py
sources/sql_database/helpers.py
tests/sql_database/test_sql_database_source.py

~~Note: this includes the commits of https://github.com/dlt-hub/verified-sources/pull/550 , will rebase after that is merged.~~
Implements `query_adapter_callback` argument for sql database. Can be used to modify or completely replace the generated sqlalchemy query, e.g.:
```python
def query_adapter_callback(query, table):
if table.name == "chat_channel":
return query.where(table.c.active.is_(True))
return query
```
Second part of https://github.com/dlt-hub/verified-sources/issues/531#issuecomment-2267646842

SQL database: query adapter callback

---

sources/mongodb/__init__.py
sources/mongodb/helpers.py
tests/mongodb/test_mongodb_source.py

feat(mongodb): implement data filter for mongodb source

---

sources/mongodb/helpers.py
sources/mongodb/requirements.txt
sources/sql_database_pipeline.py
tests/mongodb/test_mongodb_source.py
tests/rest_api/test_rest_api_source_processed.py
tests/sql_database/test_sql_database_source.py

Make pymongoarrow optional

---

sources/pg_replication/schema_types.py
sources/scraping/__init__.py
sources/scraping/runner.py

- allows scrapy to register in dlt 1.0
- allows pg_replication to import from dlt 1.0

fix scrapy source registration

---

.github/workflows/init.yml
.github/workflows/lint.yml
.github/workflows/test_all_sources_nigthly.yml
.github/workflows/test_destinations_slow.yml
.github/workflows/test_on_local_destinations.yml
.github/workflows/test_on_local_destinations_forks.yml
Makefile

Poetry 2.0 introduced breaking changes to CI and project utilities. The changes mimic [changes to the main dlt repo](https://github.com/dlt-hub/dlt/commit/c7c33709e007b32240c14bce1a77e002eefe1c5f)

pin poetry==1.8.5 in CI and Makefile

---

sources/hubspot/helpers.py
sources/mongodb/__init__.py
sources/mongodb/helpers.py
tests/mongodb/test_mongodb_source.py

- improving, documenting, or customizing an existing source (#577)
This implements two sets of features:
- Improve default behavior for `objectId` type and add `pymongoarrow_schema` for a user-facing type-casting API for `mongodb -> pyarrow`
- Add `projection` kwarg: allows to select the fields to include/exclude when pulling the data from MongoDB. This reduces egress volume and helps with regulatory compliance (e.g., don't pull sensitive information)
- Using `pymongoarrow_schema` can intersect with the column selection in `projection`. The `pymongoarrow_schema` overrides the projection kwarg.
- The `pymongoarrow_schema` will "fail silently" if you cast to an invalid type (e.g., `ObjectId` to `int`): https://github.com/mongodb-labs/mongo-arrow/issues/246
- `ObjectId` is represented as a …

mongodb: Allow projection and mongoarrow schema

---

sources/kafka/__init__.py

Fix typo, changed 'transfered' to 'transferred'
None
None

Fix typo, changed 'transfered' to 'transferred'

---

pyproject.toml
tests/utils.py

tests did no longer run because they were trying to import this exception from a wrong location.
after moving it, most passed except the workflow `tests dlt init compatibility`.
with [refactors iceberg and duckdb cache support](https://github.com/dlt-hub/dlt/pull/2430/files#top) 
the exception imported in the utils file moved.
most workflows worked correctly, except the one in `init.yml` which didn't do make dev but only installed `dltpure`-dep-group 
```
[dependency-groups]
dltpure = ["dlt>=1.7.0"]
```
I dont understand why this didnt pick up the latest then, but apparrenlty it didnt. changing it to 1.10. works though

fix: tests import exception from correct location

---

sources/stripe_analytics/README.md

The Stripe README.md mentions using `dlt init stripe duckdb` to intialize the pipeline, when it actually should be `dlt init stripe_analytics duckdb`.

Fix wrong initialization command on Stripe documentation

---

sources/inbox/README.md

Adds a hint about concurrency limits in regards to GMail access via IMAP

docs(inbox): GMail concurrency

---

sources/inbox_pipeline.py

the function (`inbox_source`) this argument is passed to, has this parameter optional. It's the first error one runs into as most likely most inboxes do not have a sender of `dlthub@dlthub.com`, meaning the generated sample code always yields an empty result.

fix(inbox): senders filter is optional

---

sources/inbox/helpers.py

- implementing verified source (please link a relevant issue labeled as `verified source`)
- anything else (please link an issue or describe below)
`Wed, 12 Jan 2022 13:08:52 GMT` is a valid RFC 2822 date, however pendulum runs into problems with it, due to the `GMT` only portion:
```
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/Users/joscha/dev/dagster-gmail-extractor/.devenv/state/venv/lib/python3.12/site-packages/pendulum/parser.py", line 36, in parse
return _parse(text, **options)
^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/joscha/dev/dagster-gmail-extractor/.devenv/state/venv/lib/python3.12/site-packages/pendu …
```

fix(inbox): RFC 2822 dates parsing

---

sources/pipedrive/__init__.py
sources/pipedrive/helpers/__init__.py
sources/pipedrive/helpers/custom_fields_munger.py
sources/pipedrive/helpers/pages.py
sources/pipedrive/settings.py

Pipedrive source should have `projects` and `tasks`
https://developers.pipedrive.com/docs/api/v1/Projects
https://developers.pipedrive.com/docs/api/v1/Tasks
The recents documentation doesn't make mention of these objects because it's an addon:
https://support.pipedrive.com/en/article/projects-by-pipedrive
VSCode also did removals of all unused imports to prevent lint complaints

update pipedrive source with projects and tasks

---

sources/google_sheets/helpers/data_processing.py
sources/pipedrive/__init__.py
tests/google_sheets/test_data_processing.py
tests/google_sheets/test_google_sheets_source.py
tests/pipedrive/test_pipedrive_source.py

This PR adjusts how the `process_range` function handles trailing empty column entries that are silently dropped in the zipping operation of the inner loop. Before handling the row values, the function now aligns the row with explicit empty values and adjusts the data_types list with None values accordingly. A test was added with cases provided by the user.
- Fixes #619

Handling of trailing undetected empty columns

---

sources/google_analytics/__init__.py
sources/google_analytics/helpers/__init__.py
sources/google_analytics/helpers/data_processing.py
tests/google_analytics/test_google_analytics_source.py

This PR enables time dimension options for the google_analytics source. Previously, the time dimension was always set to date.
Incremental test was failing due to `pendulum.test` being deprecated. This is now replaced with a forced end date in incremental column.
- Fixes #626

Adjustable time dimension for google_analytics source

---

tests/test_dlt_ai.py

This PR just removes the branch specified in the test_ai_setup_command branch. We don't need specification, since it's already merged.

Fix: test_ai_setup_comman references wrong branch

---

sources/salesforce/README.md
sources/salesforce/__init__.py
sources/salesforce/helpers.py
sources/salesforce/helpers/client.py
sources/salesforce/helpers/records.py
tests/salesforce/test_salesforce_source.py

This PR enables different auth methods for the salesforce source that are supported by the underlying simple_salesforce package.
Additionally, the standard api is enabled if bulk api is not available in Salesforce - this applies to Salesforce trial accounts that users may test this source with.  
Relates to #639

Feat: Salesforce different auth methods

---

ai/.rules/rest_api_extract_parameters.md
ai/.rules/rule.md
ai/amp/AGENT.md
ai/claude/CLAUDE.md
ai/cline/.clinerules/rest_api_extract_parameters.md
ai/cline/.clinerules/rule.md
ai/codex/AGENT.md
ai/cody/.sourcegraph/rest_api_extract_parameters.rule.md
ai/cody/.sourcegraph/rule.rule.md
ai/continue/.continue/rules/rest_api_extract_parameters.md
ai/continue/.continue/rules/rule.md
ai/copilot/.github/instructions/rest_api_extract_parameters.instructions.md
ai/copilot/.github/instructions/rule.instructions.md
ai/cursor/.cursor/rules/rest_api_extract_parameters.mdc
ai/cursor/.cursor/rules/rule.mdc
ai/windsurf/.windsurf/rules/rest_api_extract_parameters.md
ai/windsurf/.windsurf/rules/rule.md

This PR removes the unnecessary template `rule.md` and converts the markdown table in `rest_api_extract_parameters.md` to YAML format.
Resolves #633

RULES: Unnecessary template rule removed, md table made yaml

---

sources/pg_replication/schema_types.py
tests/pg_replication/cases.py
tests/pg_replication/test_pg_replication.py

This PR is a continuation of #652 that addresses the following problem: `pg_replication` source doesn't handle json (OID 114) and timestamp (OID 1114) data types correctly.
The types were added to the type mapper, along with appropriate tests.
Resolves #652

Fix: Timestamp without timezone, regular json data types in pg_replication
